FROM postgres:15

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        git \
        postgresql-server-dev-15

RUN git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install

RUN echo "CREATE EXTENSION IF NOT EXISTS vector;" > /docker-entrypoint-initdb.d/init.sql
